config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :completed_assignments
  resources :assignments
  resources :sessions

root 'sessions#new'

end

app/models/completed_assignment.rb
class CompletedAssignment < ActiveRecord::Base
  validates :url, presence: true

  belongs_to :user
  belongs_to :assignments
end

app/controllers/completed_assignments_controller.rb
class CompletedAssignmentsController < ApplicationController
  before_action :set_completed_assignment, only: [:show, :edit, :update, :destroy]
  before_action :require_login


  # GET /completed_assignments
  # GET /completed_assignments.json
  def index
    @completed_assignments = CompletedAssignment.all
  end

  # GET /completed_assignments/1
  # GET /completed_assignments/1.json
  def show
  end

  # GET /completed_assignments/new
  def new
    @completed_assignment = CompletedAssignment.new
  end

  # GET /completed_assignments/1/edit
  def edit
  end

  # POST /completed_assignments
  # POST /completed_assignments.json
  def create
    @completed_assignment = CompletedAssignment.new(completed_assignment_params)

    respond_to do |format|
      if @completed_assignment.save
        format.html { redirect_to assignments_path, notice: 'Completed assignment was successfully created.' }
        format.json { render :show, status: :created, location: @completed_assignment }
      else
        format.html { render :new }
        format.json { render json: @completed_assignment.errors, status: :unprocessable_entity }
      end
    end
    @completed_assignment.update(completed: false)
  end

  # PATCH/PUT /completed_assignments/1
  # PATCH/PUT /completed_assignments/1.json
  def update
    respond_to do |format|
      if @completed_assignment.update(completed_assignment_edit_params)
        format.html { redirect_to assignments_path, notice: 'Completed assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @completed_assignment }
      else
        format.html { render :edit }
        format.json { render json: @completed_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /completed_assignments/1
  # DELETE /completed_assignments/1.json
  def destroy
    @completed_assignment.destroy
    respond_to do |format|
      format.html { redirect_to completed_assignments_url, notice: 'Completed assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_completed_assignment
      @completed_assignment = CompletedAssignment.where(assignments_id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def completed_assignment_params
      params.require(:completed_assignment).permit(:user_id, :assignments_id, :url)
    end

    def completed_assignment_edit_params
      params.require(:completed_assignment).permit(:user_id, :assignments_id, :url, :completed)
    end
end

app/helpers/completed_assignments_helper.rb
module CompletedAssignmentsHelper
end

app/views/completed_assignments/_form.html.erb
<%= form_for(@completed_assignment) do |f| %>
  <% if @completed_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@completed_assignment.errors.count, "error") %> prohibited this completed_assignment from being saved:</h2>

      <ul>
      <% @completed_assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, value: session[:user_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :assignments_id, value: session[:assignment_id] %>
  </div>
  <% if student? %>
  <div class="field">
    <%= f.label :url, "Github URL" %><br>
    <%= f.url_field :url, placeholder: "Paste Github URL here" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Assignment for review" %>
  </div>
  <% end %>
  <% if teacher? %>
  <div>
    Completed to specifications? <%= f.check_box :completed %><br>
    <%= f.submit "Approve" %>
  </div>
  <% end %>
<% end %>

app/views/completed_assignments/edit.html.erb
<div class="container">
<h1>Editing completed_assignment</h1>

<%= render 'form' %><br>

<%= link_to 'Show', @completed_assignment %> |
<%= link_to 'Assignments', assignments_path %>
</div>

app/views/completed_assignments/index.html.erb
<h1>Listing completed_assignments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Assignments</th>
      <th>Url</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @completed_assignments.each do |completed_assignment| %>
      <tr>
        <td><%= completed_assignment.user %></td>
        <td><%= completed_assignment.assignments %></td>
        <td><%= completed_assignment.url %></td>
        <td><%= completed_assignment.completed %></td>
        <td><%= link_to 'Show', completed_assignment %></td>
        <td><%= link_to 'Edit', edit_completed_assignment_path(completed_assignment) %></td>
        <td><%= link_to 'Destroy', completed_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Completed assignment', new_completed_assignment_path %>

app/views/completed_assignments/new.html.erb
<div class="container new-completed-assignment">
  <div class="row">
    <div class="large-8 comlumns panel">
      <h3>Submit Assignment</h3>

      <%= render 'form' %>

      <%= link_to 'Back', assignments_path %>
    </div>
  </div>
</div>

app/views/completed_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @completed_assignment.user_id %>
</p>

<p>
  <strong>Assignments:</strong>
  <%= @completed_assignment.assignments_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @completed_assignment.url %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @completed_assignment.completed %>
</p>

<%= link_to 'Edit', edit_completed_assignment_path(@completed_assignment) %> |
<%= link_to 'Assignments', assignments_path %>