config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :completed_assignments
  resources :assignments
  resources :sessions

root 'sessions#new'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  validates :title, :description, :date, :due, presence: true
  validate :assign_it_before_it_is_due

  def assign_it_before_it_is_due
    if date >= due
      errors.add(:assign_it_before_it_is_due, ", the assignment can't be due before it is assigned!")
    end
  end

  def submission(student)
    student.completed_assignments.find_by_assignments_id(self.id)
  end

  def complete?(student)
    a = submission(student)
    a && a.completed == true
  end

  def for_review?(student)
    a = submission(student)
    a && a.completed == false
  end

  def incomplete?(student)
    submission(student) == nil
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :require_login
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_action :verify_teacher, only: [:new, :create, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    session[:assignment_id] = @assignment.id
    @students = User.where(teacher_id: session[:user_id])
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title, :description, :date, :due)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
    def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def active?(assignment)
    assignment.date < DateTime.now
  end

  def past?(assignment)
    assignment.due < DateTime.now
  end

  
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, default: DateTime.now.beginning_of_day %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.datetime_select :due, default: DateTime.tomorrow.beginning_of_day + 6.hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<div class="wall assignments">
  <div class="row">
    <div class="8-large comlumns">
      <h1>Homework List</h1>

      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Date</th>
            <th>Due</th>
            <% if student? %>
              <th>Status</th>
            <% end %>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @assignments.each do |assignment| %>
            <% if active?(assignment) || teacher? %>
            <tr>
              <td><%= assignment.title %></td>
              <td><%= assignment.date %></td>
              <td><%= assignment.due %></td>
              <% if student? %>
                <% if status(assignment)=="Up for review"%>
                <td><span class="radius regular label">UP FOR REVIEW</span></td>
                <% elsif status(assignment)=="Completed" %>
                <td><span class="radius success label">COMPLETE</span></td>
                <% elsif status(assignment)=="Incomplete" && past?(assignment) %>
                <td><span class="radius alert label">INCOMPLETE</span></td>
                <% else %>
                <td><span class="radius secondary label">ACTIVE</span></td>
                <% end %>
              <% end %>
              <td><%= link_to 'Show', assignment %></td>
              <% if teacher? %>
              <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
              <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <br>

      <% if teacher? %>
        <%= link_to 'New Assignment', new_assignment_path, class: "button" %>
      <% end %>
    </div>
  </div>

app/views/assignments/new.html.erb
<div class="container new-completed-assignment">
  <div class="row">
    <div class="large-8 comlumns panel">
      <h3>New assignment</h3>
      <%= render 'form' %>
      <%= link_to 'Back', assignments_path %>
    </div>
  </div>
</div>

app/views/assignments/show.html.erb
<div class="container">
<h1>
  <%= @assignment.title %>
</h1>

<p>
  <strong>Assigned:</strong>
  <%= @assignment.date.to_formatted_s(:long_ordinal) %><br>
  <strong>Due:</strong>
  <%= @assignment.due.to_formatted_s(:long_ordinal) %><br>
  <% if ((@assignment.due - DateTime.now)/3600) > 0 %>
  <strong>Hours Until Due:</strong>
  <%= ((@assignment.due - DateTime.now)/3600).to_i %>
  <% end %>
</p>

  <%= markdown(@assignment.description) %>

<% if teacher? %>
  <h3>Students</h3>
  <% @students.each do |student| %>
     <div><%= student.name %> |
           <% if @assignment.complete?(student) %>
             <span class="radius success label">COMPLETE</span> |
             <%= link_to "Submitted URL", @assignment.submission(student).url %>
           <% elsif @assignment.for_review?(student) %>
             <span class="radius regular label">UP FOR REVIEW</span> |
             <%= link_to "Submitted URL", @assignment.submission(student).url %>
           <% elsif @assignment.incomplete?(student) %>
             <span class="radius alert label">NOT SUBMITTED</span>
           <% end %>
      </div>
  <% end %>
<% end %>
<p>
  <ul class="button-group">
    <% if student? %>
    <li><%= link_to 'Submit assignment', new_completed_assignment_path, class: "button" %></li>
    <% end %>
    <li><%= link_to 'See all Assignments', assignments_path, class: "button" %><li>
  </ul>
</p>