config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :completed_assignments
  resources :assignments
  resources :sessions

root 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Homework Central", assignments_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if current_user %>
        <li><%= link_to "Logged in as #{current_user.name}", "#" %></li>
        <li class="active"><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li class="active"><%= link_to "Log In", login_path, class:"active" %></li>
        <% end %>
      </li>
    </ul>
  </section>
</nav>
<div class='wall'>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</div>
</html>